src/modules/mavlink/mavlink_mission.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/navigation.h
src/modules/navigator/navigator_main.cpp

**Describe problem solved by this pull request**
When designing mission items, all commands in said item are sent to the vehicle (except camera commands). We want the winch commands to be sent to a different component.
**Describe your solution**
MAV_CMD_DO_WINCH is added to PX4's list of supported commands. In the case of an incoming winch command, it is sent to the winch component (42) just like for camera actions.
**Describe possible alternatives**
Modifying the existing camera trigger functionality to perform winching actions.
**Test data / coverage**
Verified that commands are forwarded when mission item is reached in simulator. 
**Additional context**
See [this QGC branch](https://github.com/aviant-tech/qgroundcontrol/tree/aviant-winch-support/V4.2).

Added winch support

---

src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/modules/flight_mode_manager/tasks/AutoMapper/FlightTaskAutoMapper.cpp

If wind is too strong for the drone to hold position, time stretch can prevent the drone from ever landing. Also reset trajectory setpoint XY position when starting landing.

Disable time stretch while landing in auto

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c

We want to disable the predictive battery failsafe since the predictiveness has false positives during the VTOL transition in certain wind conditions. This commit introduces the parameter COM_PRED_BAT_FS, which controls whether the predictive battery failsafe is enabled. 
I was not sure if introducing a new parameter was necessary, but I decided to do it since we may want to use the predictive feature for longer flights without the winching-related VTOL transitions.

Make predictive battery failsafe optional

---

src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h
src/modules/navigator/rtl_params.c

**Problem this PR aims to solve:**
With a landing speed at 1 m/s, and a RTL altitude of 60 meters, a RTL in MR consumes a lot of battery. Even for start in FW, the battery usage is very high, as the drone will transition and start landing from 60 meters. Using RTL_DESCEND_ALT to descent before landing is not feasible because it needs to be set high enough to allow for FW loitering.
**Solution:**
Introduce new RTL state and parameter for descend at in MR at speed MPC_Z_VEL_MAX_DN until the altitude specified by RTL_DESCEND_MR is reached.
**Alternative solution:**
Using distance sensor during landing (available in 1.13) may allow us to use higher landing speed and fix this. This this is not verified yet. Upgrade to 1.13 is pending testing and potentially some development work.

Faster MR descend for RTL

---

boards/cubepilot/cubeorange/init/rc.board_defaults
src/modules/mavlink/mavlink_log_handler.cpp
src/modules/mavlink/mavlink_main.cpp

Note: Two of these fixes are on review upstream. Log buffer increase is only in our repo.
When increasing the log buffer size, the total RAM goes from ~45% to ~55%. The RAM usage is very stable, so this change should be fine. The previous (default) log size is 64KiB, this change doubles that to 128KiB.
For other fixes, this description is copied from upstream PR:
When upgrading a cube orange to 1.13 we found log download by USB to not work when there was 50 or more logs on the target. In addition for less than 50 logs, it is necessary to request the list of logs two times for it to be generated. This is assuming we use QGroundControl (which requests 50 entries at a time with LOG_REQUEST_LIST), and USB connection.
There is two issues that cases this:
- When opening the mavlink module by …

Logging fixes for 1.13

---

src/modules/mavlink/mavlink_main.cpp

Fixes bug with reopening of stdin/stdout/stderr in #14

Fix bug when opening /dev/null as default stdin/stdout/stderr

---

.github/workflows/compile_nuttx.yml
src/lib/mixer_module/mixer_module.cpp

Cherry pick from release/1.13 branch (after v1.13.2 release).
This fixes that pwm main/aux is allocated to actuator_outputs_2/3 instead of expected 0/1, because 0/1 is allocated to unused uavcan pwn outputs.
Fixing this uORB message, will fix both log and Mavlink message SERVO_OUTPUT_RAW.

mixer_module: only advertise actuator_outputs when mixer is loaded

---

src/modules/navigator/navigator_main.cpp

In 1.13, if reposition outside geofence during a mission with VTOL transition, the drone will return to home and circle there in a very tight circle, rather than loiter at current position as is behavior in 1.12 and main.
This behavior does not happen if a valid reposition, or one of a number of other commands are given prior to the reposition outside the geofence.
The cherry picked commit fixes the 1.13 behavior to be as expected.
Screenshot is from simulator, but the same behavior can be found in https://fms.aviant.no/flight/2329/show

Fix return to home if reposition outside geofence

---

platforms/nuttx/src/px4/common/px4_init.cpp

For some reason, the same behavior is hard to get on a test setup connected directly to the cube, but it is very repeatable on NT11. It could be that the length of wires impacts the cubes ability to pull down I2C lines.
I2C data line is pulled up by distance sensor after this command, so that it will not reach 0 (rather about 1 - 1.5 V) when the master try to send. It might be that the distance sensor enters UART mode, but this is not verified.
Unplugging/re-plugging the distance sensor after boot fixes this, and everything runs normal after (after manually restarting drivers for airspeed and distance sensor).
The fix impacts start up only, so it will be safe in air, as long as all drivers started as expected.

Distance sensor 1.13 issue quick fix

---

src/modules/navigator/mission_block.cpp

This PR reverts part of changed to WP acceptance check introduced between 1.12 and 1.13, so that the loiter to altitude (when WP altitude is not reached) have the same end behavior.
Before (1.13 behavior):
After (same as 1.12):
For comparison, master branch, which have similar 1.12 behavior, but this is unintended, because of a bug:

1.13 loiter to altitude issue

---

src/modules/commander/Commander.cpp

QGC does not send "Terminate", but disarm signal.
When disarming in the air, we should trigger parachute.
Alternative solution:
Modify QGC to send terminate.
To be tested:

Send parachute command on disarm in air

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp

#23 ported to 1.13
Also add missing definition of COM_PARACHUTE, so that this parameter is available to set (require healthy parachute to arm).

Send parachute command on disarm in air - 1.13

---

msg/failure_detector_status.msg
src/modules/commander/Commander.cpp
src/modules/commander/failure_detector/FailureDetector.cpp
src/modules/commander/failure_detector/FailureDetector.hpp
src/modules/commander/failure_detector/failure_detector_params.c

New parameters:
- `FD_MPC_VZ_THR` Threshold - descend at at least this velocity while setpoint is "ascending"
- `FD_MPC_VZ_TTRI` Trigger time - conditions must be active for at least this long
Other relevant parameters:
- `COM_LKDOWN_TKO` If takeoff was within this time, failure detection will trigger lookdown
- `CBRK_FLIGHTTERM` Set to 0 to enable failure detector to terminate flight (if COM_LKDOWN_TKO have passed)
Note: We might want to increase COM_LKDOWN_TKO, as a parachute deployment within the current used 3 seconds probably won't do any good.

Failure detection for vertical rate

---

src/modules/commander/Commander.cpp

Use COM_LKDOWN_TKO when a disarm while in the air is received to decide if the parachute should be deployed.
Currently, if the drone detect takeoff right after landing (possibly due to landing on uneven ground), the pilot will manually disarm the drone. This may trigger the parachute. This PR, in combination with increasing COM_LKDOWN_TKO will fix this.

Do not deploy parachute on disarm right after takeoff

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/failure_detector/FailureDetector.cpp
src/modules/commander/failure_detector/FailureDetector.hpp
src/modules/commander/failure_detector/failure_detector_params.c

This solution introduces the parameter **FD_MIN_DIST_TRM**, which acts as the minimum distance from the ground required for triggering the failsafe. If the vehicle's distance from the ground is below the specified threshold, the termination will not activate. However, the pilot will receive a warning indicating a detected anomaly, and the failure will be logged within the system for future debugging purposes.
To implement this logic, two values from the uORB message `vehicle_local_position` were utilized:
-  The `dist_bottom` parameter determines the vertical distance between the vehicle and the ground. This value is a filtered result from the distance sensor, merged with IMU data. This approach ensures that any short-term errors from the distance sensor won't introduce inaccuracies into …

commander: add ground distance check to prevent flight termination

---

src/modules/mavlink/mavlink_main.cpp

Add ATTITUDE and TIMESYNC message to custom MAVLink mode.
For use with custom AVSS parachute. The ATTITUDE messages are used as a
"fast heartbeat", and TIMESYNC is needed to synchronise the clock used in parachute logs.

Custom mavlink mode for parachute

---

src/modules/commander/state_machine_helper.cpp

**Describe problem solved by this pull request**
When flying by RC, I want the Quadchute failsafe to save the aircraft if something goes wrong. Without this fix, the aircraft would remain in its previous flight mode, which can in some situations be even more dangerous than not quadchuting, since the pilot has very little time to react.
**Test data / coverage**
It is tested by connecting the remote controller to my computer and triggering the minimum altitude quadchute in SITL for Stabilized and Position flight modes, and observing that the drone RTLs as expected.

commander: Respect COM_QC_ACT in manual flight modes

---

src/modules/logger/logged_topics.cpp

These are used by VTOL vehicles. MC virtual attitude setpoint is relevant for tuning pusher assist, as it shows what the pitch setpoint is before the pusher assist code changes it.

logger: log viertual attitude setpoints

---

src/modules/ekf2/EKF/estimator_interface.h

Because we want to log these events in non-debug builds without alerting the pilot
This would have been extremely useful in the recent EKF troubleshooting processes

ekf2: Redefine ECL_ERR from PX4_DEBUG to PX4_INFO

---

src/modules/vtol_att_control/vtol_att_control_main.cpp

**Describe the problem solved by this pull request**
When VTOL enters a failsafe while transitioning is not possible to retake control over the vehicle. 
This is an edge case that was not previously properly addressed. 
**Describe your solution**
This solution will exit from the failsafe if an external command arrives.

vtol_att_control: allow override failsafe mode with external commands

---

src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h

Previously, vtol_transition_failsafe would be published in one iteration of the loop in vtol_att_control, while vtol_in_rw_mode based on vtol_transition_failsafe would be updated in the next. This could cause RTL to create a mission item for MR while the navigator still uses FW mode for calculating acceptance radius using in the RTL mission item.
Before using, we should probably test a bit more in simulator, and check other places in the code that the flags are used, to see if this can cause unintended changes as well. But should be OK for a core review.
EDIT: Have checked more in code, without finding anywhere else where this should be an issue. Tested in simulator.

vtol_att_control: publish vtol_transition_failsafe and vtol_in_rw_mode in same update

---

src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp
src/modules/navigator/navigator_params.c

For traffic avoidance, this adds the option to give a range of icao
addresses that will not trigger the configured traffic avoidance action.
Can be used to ignore an external transponder in the vehicle, or other
vehicles in the same fleet.

Add option to ignore a range of icao addresses

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h

This PR provides logic to prevent early transition (MC to FW) due to airspeed measurement spikes. <
**Issue**
The airspeed value (calibrated_airspeed_m_s) that is used for comparing it with the `VT_ARSP_TRANS` parameter can have spikes that can cause to early transition to FW that can cause issues such as vehicle entering into the **under-speed state**, and other issues since the vehicle didn't develop real speed for transition to fixed-wing state. 
The image shows very high-value spikes that are happening in single samples: 
**Solution**
The solution in this PR will check for consecutive calibrated_airspeed_m_s to be higher than the parameter `VT_ARSP_TRANS` for 250 ms. The sample rate inside the airspeed_validated module is 100ms, so this means that 3 consecutive samples will be checked …

vtol_att_control: check airspeed for a time period before the transition

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/gps_checks.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c

Use parameter value instead of hard coded 3 (3D fix). We do not allow
for less fix, but can require DGNSS/RTK fix in order to start using the
GNSS.
Note: we will need to redo this for dual GPS setup later

ekf2: add parameter for minimum gnss fix type required

---

src/modules/mavlink/mavlink_mission.cpp
src/modules/navigator/navigation.h
src/modules/navigator/rtl.cpp

**This PR should be test flown before merge**
Need new QGC features https://github.com/aviant-tech/qgroundcontrol/pull/25
Rally points can now be always active (default/old behavior) or setup to
only be valid for either MR or FW flight.
Uses parameter 1 in the MAVLink message
(https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_RALLY_POINT) to
set type, 0=Always, 1=MR only, 2=FW only.

Add support for rally point types

---

src/modules/navigator/rtl.cpp

This is the same behavior as in 1.14 (fixed in
https://github.com/PX4/PX4-Autopilot/pull/19928), and as described in
the documentation for RTL_RETURN_ALT.

rtl: return at RTL_RETURN_ALT above destination, not home

---

src/drivers/uavcan/sensors/battery.cpp
src/drivers/uavcan/sensors/battery.hpp
src/drivers/uavcan/sensors/sensor_bridge.cpp
src/drivers/uavcan/uavcan_params.c

Makes the UavcanBatteryBridge bidirectional, so it can publish uORB -> UAVCAN in addition to the existing UAVCAN -> uORB
UAVCAN_PUB_BAT: Turns on/off publishing from uORB -> UAVCAN
UAVCAN_BAT_RATE: Max rate for publishing to UAVCAN
Our own UAVCAN broadcasts will not trigger the listener callback, so we don't have to worry about loops.

[WIP] uavcan: publish battery status over uavcan

---

src/drivers/batt_smbus/batt_smbus.cpp
src/drivers/batt_smbus/batt_smbus.h

This is only intended for test flights. Note that the base branch `aviant/bms_test_flights` is flight-worthy, but not  production-grade.
If this is to be used in prod, a thorough review of the combined changes should be performed.

BMS driver fixes

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

Got low stack warnings with the new UAVCAN battery publishing feature. 4000 is chosen arbitrarily, a nice round number.

Increase wq:uavcan stack to 4000

---

msg/vtol_vehicle_status.msg
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

This solves an issue where spikes in airspeed values would cause oscillations in blending weights and in turn strong throttle oscillations, impairing transition performance.
Airspeed measurements are filtered using a 1st order IIR low-pass filter which accounts for sample rate.
The filter time constant is controlled using parameter VT_ARSP_TAU.
In addition, it acts as a more robust replacement for the existing logic to prevent airspeed spikes affecting transition acceptance.

vtol_att_control: use filtered airspeed for forward and backtransition acceptance & blending

---

.gitmodules
src/drivers/uavcan/sensors/gnss.cpp
src/drivers/uavcan/sensors/gnss.hpp
src/drivers/uavcan/uavcan_params.c
src/modules/sensors/vehicle_gps_position/gps_blending.cpp
src/modules/sensors/vehicle_gps_position/gps_blending_test.cpp

For differential yaw to work, MovingBaselineData must be sent from the moving base GPS to the rover gps. This currently happens automatically if they are on the same CAN bus. However, for redundancy, we want the GPSes on different buses.
This PR adds the possibility for forwarding MovingBaselineData from one CAN bus to another. The original sender's node ID is preserved, and the message is only forwarded to the other can interfaces - not the one where it arrived. In order to do this, updates to libuavcan were required. Therefore, the original submodule pointer is replaced with our fork.
Forwarding of MBD is controlled with the new parameter UAVCAN_FWD_MBD.
In addition, this PR adresses a bug where the time_utc_usec field isn't populated when blending multiple GPSes. This fix has already …

uavcan: Forward MovingBaselineData between CAN interfaces

---

msg/estimator_status.msg
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/EKF2Selector.cpp
src/modules/ekf2/EKF2Selector.hpp
src/modules/ekf2/ekf2_params.c

This PR adds the possibility to run multiple EKF instances, so that there are separate instances for GNSS-based navigation and navigation with only visual odometry. The parameter `EKF2_MULTI_VIS` enables or disables this functionality.
The existing pattern used for multi-imu and multi-mag EKF is extended with another dimension for multi-vision. EKF instances configured for vision discard GNSS samples, and instances configured for GNSS discards optical flow and visual odometry samples.
An exception is made while disarmed, where the vision-based estimators will get GPS data, in order to automatically initialize position during testing. 
For initial testing, we don't want to fly on the vision estimators. For flights using vision estimators, the flight mode is used to determine the EKF …

Testing GNSS-denied navigation with VO

---

src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/MulticopterPositionControl.hpp
src/modules/mc_pos_control/mc_pos_control_params.c

Introduce a low-pass filter for velocity measurements used by the multicopter velocity controller.
We have problems with oscillations on the drone that likely stem from the velocity controller giving out acceleration setpoints that have a bandwidth that is higher than what the drone dynamics and attitude controller can handle.
By limiting the bandwidth of velocity controller input signal, the output bandwidth wil also be limited. This works in a similay way to how the D term is band limited already. A new parameter, MPC_VEL_LP, controls this functionality.
**Why the seemingly "hacky" behaviour of disabling the filter by setting it to a high value?**
The `control::BlockLowPass` which is used for the filtering, takes in a cutoff frequency, and due to the way `control::Block` deals with …

mc_pos_control: Low-pass filter velocity measurements

---

src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

We want to be able to have different LPF cutoffs for XY velocity and Z velocity, so we can tune XY tracking without affecting descend speed.

mc_pos_control: different LPF cutoffs for XY and Z

---

.gitignore
msg/estimator_selector_status.msg
src/modules/commander/Commander.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/commander/state_machine_helper.h
src/modules/ekf2/EKF2Selector.cpp
src/modules/ekf2/EKF2Selector.hpp
src/modules/ekf2/ekf2_params.c
src/modules/ekf2/ekf2_params_selector.c

This enables selection of GNSS-denied EKF instances, depending on the parameter EKF2_SEL_GNSSDEN. Will fly GNSS-denied in MISSION or OFFBOARD flight modes. The functionality has been tested in sim using failure injection.
If any failsafe triggers, we will latch as GNSS-enabled until reboot.
Also, the termination action is disabled for position loss failsafes while a GNSS-denied EKF instance is selected, with a 1 second grace period. This is necessary to avoid unnecessary parachute landings. I don't like passing estimator_selector_status through `set_nav_state` to `check_invalid_pos_nav_state` for this feature, but I think it's good enough for our current use case.

Enable GNSS-denied flight with fallback in case of failsafe

---

src/modules/commander/state_machine_helper.cpp

This should fix the "repeated trigger of offboard loss failsafe" behaviour observed in https://aviant.atlassian.net/wiki/spaces/TECHNICAL/pages/1086029828/2024-08-28+NX02+Unexpected+behaviour+after+offboard+control+lost
Also noticed that LAND offboard failsafe did not work without global position, so I just fixed it while I was there

Fix main state changes in offboard loss failsafe

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/estimator_interface.cpp
src/modules/ekf2/EKF/estimator_interface.h
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/EKF2Selector.cpp
src/modules/ekf2/EKF2Selector.hpp
src/modules/ekf2/ekf2_params.c
src/modules/ekf2/ekf2_params_selector.c

Alternative to https://github.com/aviant-tech/PX4-Autopilot/pull/70 for true GNSS-denied flight, inspired by LPE_FAKE_ORIGIN
The main advantage of this approach is that it only affects the explicitly GNSS-denied EKF instances, so it can be tested with GPS fallback.

Fake origin for GNSS-denied EKF2 instances

---

src/modules/logger/logged_topics.cpp

The data is typically received at 5 Hz, and we want to log everything
for troubleshooting and analysis.

logger: log GNSS data at max rate

---

src/modules/logger/logged_topics.cpp
src/modules/logger/logged_topics.h
src/modules/logger/params.c

This adds high rate (400Hz) logging for the undampened IMU, but also
removes some topics compared to the stock high rate log mode to keep the
total log amount and used CPU and bandwidth manageable.
Before merge
We should also setup parameter monitoring to track `SDLOG_PROFILE` when released.

Add Aviant high rate log mode
